blank_issues_enabled: false
issue_templates:
  - name: Bug Report
    description: Report a bug to help us improve ğŸ
    file: bug_report.md
  - name: Feature Template
    description: Suggest an feature for this project ğŸ‘©â€ğŸ’»
    file: feature.md
  - name: Question Template
    description: Ask a question about this project ğŸ¤·ğŸ»â€â™€ï¸
    file: question.md
